/* ============================================================
   Interactive embed: MapLibre map + D3 popup + D3 legend.
   ============================================================ */

const ALL_YEARS = [1961, 1971, 1981, 1991, 2001, 2011, 2021, 2024];

// 10 fixed bins (slider-period agnostic).
const PCT_BINS = [-25, -15, -8, -3, 0, 5, 15, 35, 75];
const ABS_BINS = [-20000, -10000, -5000, -1000, 0, 1000, 5000, 10000, 20000];

// Discrete diverging palette — 10 colours (5 red + 5 green, skipping the
// cream centre so 0 is a clean red→green boundary).
const COLORS = [
  "#d46780", // 0 darkest red   — ≤−80% / ≤−20k
  "#df91a3", // 1
  "#e8acb3", // 2
  "#f0c6c3", // 3
  "#f7e1d4", // 4 lightest red  — −20→0 / −1k→0
  "#e7e7c3", // 5 lightest green— 0→+50 / 0→+1k
  "#d0d3a2", // 6
  "#bac082", // 7
  "#8e9847", // 8
  "#646c1d", // 9 darkest green — ≥+500% / ≥+20k
];

const NO_DATA_COLOR = "rgba(0,0,0,0)";    // transparent → basemap shows through

// ---- State ----------------------------------------------------------------
let yearA = 1961;
let yearB = 2024;
let mode = "pct";
let map;

// ---- Helpers --------------------------------------------------------------
function binIndex(value, bins) {
  if (value == null || !isFinite(value)) return null;
  for (let i = 0; i < bins.length; i++) {
    if (value < bins[i]) return i;
  }
  return bins.length;
}

// Walk forward (+1) or backward (-1) from `requested` until we find a year
// that this feature has data for. Used for the popup info-sentence so the
// UK (no 2024 data) reads as "between 1961 and 2021".
function effectiveYear(props, requested, direction) {
  const k = "pop_" + requested;
  if (props[k] != null) return [requested, props[k]];
  const range = direction < 0
    ? ALL_YEARS.filter(y => y < requested).reverse()
    : ALL_YEARS.filter(y => y > requested);
  for (const y of range) {
    if (props["pop_" + y] != null) return [y, props["pop_" + y]];
  }
  return [requested, null];
}

function formatAbsLabel(v) {
  const sign = v > 0 ? "+" : (v < 0 ? "−" : "");
  const abs = Math.abs(v);
  if (abs >= 1000) return sign + (abs / 1000) + "k";
  return sign + abs;
}

// ---- Paint expression for the choropleth ---------------------------------
// MVT properties carry the full pop_1961…pop_2024 series, so the fill
// colour is computed entirely in the paint expression — one
// setPaintProperty call per slider/mode change, not a per-LAU loop.
//
// For UK gemeenten pop_2024 is null (the JRC dataset stops at 2021 for
// the UK). When yearB=2024 we coalesce to pop_2021 so the UK still gets
// a colour. All other years are straight property reads.
function getPopExpr(year) {
  if (year === 2024) {
    return ["coalesce", ["get", "pop_2024"], ["get", "pop_2021"]];
  }
  return ["get", "pop_" + year];
}

function buildFillExpr(yA, yB, modeStr) {
  const bins = modeStr === "pct" ? PCT_BINS : ABS_BINS;
  const popA = getPopExpr(yA);
  const popB = getPopExpr(yB);
  const valExpr = modeStr === "pct"
    ? ["*", 100, ["/", ["-", popB, popA], popA]]
    : ["-", popB, popA];
  return [
    "case",
    ["any",
      ["==", popA, null],
      ["==", popB, null],
      ["==", popA, 0],
    ], NO_DATA_COLOR,
    [
      "step", valExpr,
      COLORS[0],
      bins[0], COLORS[1],
      bins[1], COLORS[2],
      bins[2], COLORS[3],
      bins[3], COLORS[4],
      bins[4], COLORS[5],
      bins[5], COLORS[6],
      bins[6], COLORS[7],
      bins[7], COLORS[8],
      bins[8], COLORS[9],
    ],
  ];
}

// ---- Map setup ------------------------------------------------------------
// Protomaps basemap. Open-source vector tiles built from OpenStreetMap and
// Natural Earth, served as a single .pmtiles file (range-fetched, just like
// our own LAU layer). The visual style is generated by `protomaps-themes-base`,
// loaded as a <script> in index.html.
//
// ┌──────────────────────────────────────────────────────────────────────────┐
// │  TO ACTIVATE:                                                            │
// │   1. Sign up at https://protomaps.com (free, ~60 seconds)                │
// │   2. Copy your API key from https://app.protomaps.com                    │
// │   3. Replace the value of PROTOMAPS_KEY below                            │
// │   4. (Optional but recommended) restrict the key to your GitHub Pages    │
// │      origin in the Protomaps dashboard so nobody else can use it         │
// └──────────────────────────────────────────────────────────────────────────┘
const PROTOMAPS_KEY = "d3b78e1318dd7bcb";
const PROTOMAPS_FLAVOR = "white";    // try: light, dark, white, black, grayscale, contrast

// Fall back to OpenFreeMap (free, no key) when no Protomaps key has been
// pasted in — useful for local dev. Make sure the Protomaps key's CORS
// allowlist matches the deployment origin before going to production.
const USE_PROTOMAPS = PROTOMAPS_KEY !== "PASTE_YOUR_PROTOMAPS_KEY_HERE";

function buildProtomapsStyle() {
  // Compose a MapLibre style: Protomaps' hosted vector tiles + theme layers
  // from protomaps-themes-base + their hosted fonts/sprite assets.
  //
  // The hosted API serves traditional XYZ MVT tiles, not a single PMTiles
  // archive. We point MapLibre at the TileJSON descriptor (.json) — it auto-
  // discovers the {z}/{x}/{y}.mvt URL pattern + zoom range from there.
  //
  // Quirk: in protomaps-themes-base 4.5.0 the `layers(source, flavor)`
  // shortcut produces layer definitions WITHOUT line-color set (MapLibre
  // then rejects every line layer with `color expected, undefined found`).
  // The `default` export — same args plus a language — does the theme→layer
  // colour merge properly, so we use that one.
  return {
    version: 8,
    glyphs: "https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf",
    sprite: `https://protomaps.github.io/basemaps-assets/sprites/v4/${PROTOMAPS_FLAVOR}`,
    sources: {
      protomaps: {
        type: "vector",
        url: `https://api.protomaps.com/tiles/v4.json?key=${PROTOMAPS_KEY}`,
        attribution:
          '<a href="https://protomaps.com" target="_blank" rel="noopener">Protomaps</a> © ' +
          '<a href="https://openstreetmap.org" target="_blank" rel="noopener">OpenStreetMap</a>',
      },
    },
    // Third arg = label language. Protomaps supports ~40 ISO-639-1 codes
    // (see `protomaps_themes_base.language_script_pairs` for the full list).
    layers: protomaps_themes_base.default("protomaps", PROTOMAPS_FLAVOR, "nl"),
  };
}

const MAP_STYLE = USE_PROTOMAPS
  ? buildProtomapsStyle()
  : "https://tiles.openfreemap.org/styles/liberty";
// The exact id of the basemap's country-border layer differs per provider
// (OpenFreeMap uses `boundary_2`, MapTiler bright-v2 uses something like
// `Boundary - Country`, CARTO uses `boundary_country_inner`, …). We pick
// it up at runtime by scanning the loaded style.
function findCountryBorderLayer() {
  const layers = map.getStyle().layers;
  // Heuristic: line layer whose id mentions country / admin-0 / boundary_2,
  // skipping the disputed/halo/shadow variants.
  const looksLikeBorder = (id) => {
    const s = id.toLowerCase();
    if (!/country|admin[-_]?0|boundary[-_]?2/.test(s)) return false;
    if (/(disputed|halo|shadow|casing|maritime|coast)/.test(s)) return false;
    return true;
  };
  const lineLayers = layers.filter(l => l.type === "line");
  return (
    lineLayers.find(l => looksLikeBorder(l.id))?.id ??
    lineLayers.find(l => l.id.toLowerCase().includes("boundary"))?.id ??
    null
  );
}

async function init() {
  // Register the PMTiles protocol once, so MapLibre can fetch tile bytes via
  // HTTP range requests against our static .pmtiles file instead of
  // downloading + tessellating a 50 MB GeoJSON up front.
  const protocol = new pmtiles.Protocol();
  maplibregl.addProtocol("pmtiles", protocol.tile);

  map = new maplibregl.Map({
    container: "map",
    style: MAP_STYLE,
    center: [12, 53],
    zoom: 3.4,
    minZoom: 2,
    maxZoom: 12,
    // No built-in attribution control — we render 'Data: JRC. Kaart:
    // Protomaps / OSM.' ourselves in the legend footer, so the MapLibre
    // 'i' button would be a redundant duplicate.
    attributionControl: false,
  });

  map.on("load", () => {
    // Find the basemap's country-border layer once, then reuse for both the
    // dark-grey paint override and for the LAU layers' `beforeId`.
    const borderLayerId = findCountryBorderLayer();
    if (borderLayerId) {
      map.setPaintProperty(borderLayerId, "line-color", "#333");
      map.setPaintProperty(borderLayerId, "line-width", 1.2);
      // Protomaps' "white" flavor uses a zoom-dependent line-dasharray that
      // kicks in around zoom 4 ([2,1] = 2px on, 1px off). At our continental
      // default zoom that reads as a dotted line. Override with [1] = solid.
      map.setPaintProperty(borderLayerId, "line-dasharray", [1]);
    }

    // Tint seas/oceans a soft light blue. Protomaps' "white" flavor paints
    // water in the same near-white grey as everything else (#dcdcdc), which
    // makes the map's land and water indistinguishable. We override the
    // single `water` layer here so seas read as water without competing
    // visually with the choropleth on top.
    if (map.getLayer("water")) {
      map.setPaintProperty("water", "fill-color", "#dbe9f4");
    }

    // Darken country labels. Protomaps' "white" flavor sets `places_country`
    // text colour to #b8b8b8 — barely readable against the near-white land.
    // We bump them to the same dark grey (#5c5c5c) the theme uses for
    // city labels (`places_locality`), so countries are as easy to read.
    if (map.getLayer("places_country")) {
      map.setPaintProperty("places_country", "text-color", "#5c5c5c");
    }

    // Push city / hamlet labels later than Protomaps' defaults so a
    // continental-zoom view doesn't get crowded with small-town labels.
    // Each place feature carries a `min_zoom` (the zoom from which
    // Protomaps would naturally start showing it). We require the
    // current zoom to be ≥ that value + LABEL_DELAY.
    const LABEL_DELAY = 2;
    ["places_locality", "places_subplace", "places_region"].forEach(id => {
      if (!map.getLayer(id)) return;
      const existing = map.getFilter(id) ?? ["all"];
      const stricter = [
        ">=", ["zoom"],
        ["+", ["coalesce", ["get", "min_zoom"], 0], LABEL_DELAY],
      ];
      map.setFilter(id, ["all", existing, stricter]);
    });

    map.addSource("lau", {
      type: "vector",
      // lau-scrolly.pmtiles bakes the full 1961–2024 population series
      // into each feature's MVT properties (built by
      // rebuild_lau_scrolly_pmtiles.py). The paint expression on lau-fill
      // computes the bin entirely from feature properties — no JS-side
      // setFeatureState iteration is needed when the slider/mode changes.
      url: "pmtiles://data/lau-scrolly.pmtiles",
    });
    // If the basemap exposes a country-border layer we pass its id as
    // `beforeId` so MapLibre inserts our choropleth *under* it (so the borders
    // stay crisply on top). If no such layer was found (very minimal style)
    // beforeId stays undefined and our layers go on top.
    const beforeId = borderLayerId ?? undefined;

    map.addLayer({
      id: "lau-fill",
      type: "fill",
      source: "lau",
      "source-layer": "lau",   // matches `-l lau` passed to tippecanoe
      paint: {
        "fill-color": buildFillExpr(yearA, yearB, mode),
        "fill-opacity": 0.85,
        "fill-outline-color": "rgba(255,255,255,0)",
      },
    }, beforeId);

    // Thin white separator between adjacent LAUs; zoom-interpolated so it's
    // invisible at continental zoom and fades in around city level.
    map.addLayer({
      id: "lau-outline",
      type: "line",
      source: "lau",
      "source-layer": "lau",
      paint: {
        "line-color": "rgba(255,255,255,0.75)",
        "line-width": [
          "interpolate", ["linear"], ["zoom"],
          5, 0,
          6, 0.2,
          7, 0.4,
          8, 0.6,
        ],
      },
    }, beforeId);

    // Hover ring — also goes below the country border so it doesn't fight it
    // visually around national edges.
    map.addLayer({
      id: "lau-hover",
      type: "line",
      source: "lau",
      "source-layer": "lau",
      paint: {
        "line-color": "#222",
        "line-width": 2,
        "line-opacity": [
          "case",
          ["boolean", ["feature-state", "hover"], false], 1,
          0,
        ],
      },
    }, beforeId);

    attachInteractions();
    updateLegend();
    updateTitle();
  });
}

// Re-render the choropleth for the current (yearA, yearB, mode). One
// setPaintProperty call — MapLibre re-evaluates the fill expression for
// every visible feature on its own.
function updateMap() {
  map.setPaintProperty("lau-fill", "fill-color", buildFillExpr(yearA, yearB, mode));
  updateLegend();
  updateTitle();
}

function updateTitle() {
  document.getElementById("period-title").textContent = "Bevolkingsevolutie in Europa";
}

// 2-handle range slider over ALL_YEARS. We use integer indices (0..7)
// internally so noUiSlider gets uniform step=1; the tooltips and pips display
// the actual year via the `format` / `pips.format` callbacks.
function setupYearSlider() {
  const sliderEl = document.getElementById("year-slider");
  noUiSlider.create(sliderEl, {
    start: [0, ALL_YEARS.length - 1],
    step: 1,
    connect: true,
    range: { min: 0, max: ALL_YEARS.length - 1 },
    margin: 1,                       // handles must stay ≥1 step apart
    tooltips: [
      { to: v => ALL_YEARS[Math.round(v)], from: v => parseInt(v) },
      { to: v => ALL_YEARS[Math.round(v)], from: v => parseInt(v) },
    ],
    pips: {
      mode: "values",
      values: ALL_YEARS.map((_, i) => i),
      density: -1,
      format: { to: v => ALL_YEARS[Math.round(v)] },
    },
  });

  // Title is static — period is communicated by the slider tooltips and
  // by the trend-chart sentence in the popup.

  // On release, swap the fill expression + re-render the currently-shown
  // popup if any. Cheap — no per-feature JS loop.
  sliderEl.noUiSlider.on("change", (_v, _h, unencoded) => {
    yearA = ALL_YEARS[Math.round(unencoded[0])];
    yearB = ALL_YEARS[Math.round(unencoded[1])];
    updateMap();
    const panel = document.getElementById("chart-panel");
    if (panel.style.display !== "none" && panel.dataset.location) {
      showPopup(panel.dataset.location);
    }
  });
}

// ---- Interactions ---------------------------------------------------------
let hoveredId = null;
let pinnedId = null;   // integer feature.id locked in via click; null = popup follows hover

function attachInteractions() {
  map.on("mousemove", "lau-fill", (e) => {
    if (!e.features || e.features.length === 0) return;
    const f = e.features[0];
    const id = f.id;          // numeric idx, baked into the MVT
    if (id === hoveredId) return;
    if (hoveredId != null) {
      map.setFeatureState({ source: "lau", sourceLayer: "lau", id: hoveredId }, { hover: false });
    }
    hoveredId = id;
    map.setFeatureState({ source: "lau", sourceLayer: "lau", id }, { hover: true });
    map.getCanvas().style.cursor = "pointer";
    if (pinnedId == null) {
      showPopup(f);
    }
  });
  map.on("mouseleave", "lau-fill", () => {
    if (hoveredId != null) {
      map.setFeatureState({ source: "lau", sourceLayer: "lau", id: hoveredId }, { hover: false });
      hoveredId = null;
    }
    map.getCanvas().style.cursor = "";
    if (pinnedId == null) {
      setPopupShown(false);
    }
  });
  map.on("click", "lau-fill", (e) => {
    if (!e.features || e.features.length === 0) return;
    pinnedId = e.features[0].id;
    showPopup(e.features[0]);
  });

  setupYearSlider();

  // Mode toggle (% / abs) — same single-paint-property update path.
  document.querySelectorAll('input[name="mode"]').forEach(inp => {
    inp.addEventListener("change", (e) => {
      mode = e.target.value;
      updateMap();
      const panel = document.getElementById("chart-panel");
      if (panel.style.display !== "none" && panel.dataset.location) {
        showPopup(panel.dataset.location);
      }
    });
  });

  // Close button — clears the pin too so hover-preview resumes.
  document.getElementById("close-button").addEventListener("click", (e) => {
    e.preventDefault();
    pinnedId = null;
    setPopupShown(false);
  });
}

// ---- Popup with D3 line chart --------------------------------------------
// Accepts either a feature object (from hover/click — fastest, no lookup)
// or a gisco_id string (resume-from-slider-change path — looks up via
// querySourceFeatures).
function showPopup(featureOrGiscoId) {
  let props;
  if (typeof featureOrGiscoId === "string") {
    const matches = map.querySourceFeatures("lau", {
      sourceLayer: "lau",
      filter: ["==", ["get", "gisco_id"], featureOrGiscoId],
    });
    if (!matches[0]) return;
    props = matches[0].properties;
  } else if (featureOrGiscoId && featureOrGiscoId.properties) {
    props = featureOrGiscoId.properties;
  } else {
    return;
  }

  const locationId = props.gisco_id;
  const name = props.name || locationId;
  const panel = document.getElementById("chart-panel");
  panel.dataset.location = locationId;

  // Effective years: fall forward for the start year, backward for the end
  // year. Handles UK 2024 → 2021 and any other gaps in the JRC series.
  const [eya, pa] = effectiveYear(props, yearA, +1);
  const [eyb, pb] = effectiveYear(props, yearB, -1);

  let sentence;
  if (pa == null || pb == null || eya >= eyb) {
    sentence = `<strong>${name}</strong>: geen vergelijkbare data voor deze periode.`;
  } else {
    const delta = mode === "pct" ? (pb - pa) / pa * 100 : pb - pa;
    if (mode === "pct") {
      const verb = delta >= 0 ? "groeide" : "daalde";
      const pct = Math.abs(delta).toFixed(1).replace(".", ",");
      sentence = `In <strong>${name}</strong> ${verb} het aantal inwoners met ` +
                 `<strong>${pct}%</strong> tussen ${eya} en ${eyb}.`;
    } else {
      const abs = Math.abs(delta).toLocaleString("nl-BE");
      const verb = delta >= 0 ? "won" : "verloor";
      sentence = `<strong>${name}</strong> ${verb} <strong>${abs}</strong> ` +
                 `inwoners tussen ${eya} en ${eyb}.`;
    }
  }
  document.getElementById("info-sentence").innerHTML = sentence;

  // Line chart between the slider's effective endpoints — so picking
  // 2001 → 2024 on the slider draws the chart from 2001 to 2024, not
  // the full 1961-2024 series. eya/eyb already handle the UK 2024→2021
  // fallback so a UK municipality with slider on 2024 ends at 2021.
  const series = ALL_YEARS
    .filter(y => y >= eya && y <= eyb)
    .map(y => ({ year: y, pop: props["pop_" + y] }))
    .filter(d => d.pop != null);

  renderTrendChart(series);
  setPopupShown(true);
}

// Single source of truth for showing/hiding the popup panel. Mirrors the
// state onto <body class="popup-open"> so the legend can step aside on
// mobile (where there's no room for both side by side).
function setPopupShown(shown) {
  document.getElementById("chart-panel").style.display = shown ? "block" : "none";
  document.body.classList.toggle("popup-open", shown);
}

function renderTrendChart(series) {
  const W = 380, H = 120;
  const margin = { top: 15, right: 60, bottom: 20, left: 60 };
  const innerW = W - margin.left - margin.right;
  const innerH = H - margin.top - margin.bottom;

  const container = d3.select("#popup_chart");
  container.selectAll("svg").remove();

  if (series.length < 2) {
    container.append("p").text("Not enough data to plot.");
    return;
  }

  const svg = container.append("svg")
    .attr("viewBox", `0 0 ${W} ${H}`)
    .attr("preserveAspectRatio", "xMidYMid meet");
  const g = svg.append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

  const x = d3.scaleLinear()
    .domain([series[0].year, series[series.length - 1].year])
    .range([0, innerW]);
  // Y-axis starts at 0 so a rising/falling line can be judged against
  // the absolute population, not just the visible range.
  const y = d3.scaleLinear()
    .domain([0, d3.max(series, d => d.pop)]).nice()
    .range([innerH, 0]);

  g.append("g")
    .attr("transform", `translate(0,${innerH})`)
    .call(d3.axisBottom(x).tickFormat(d3.format("d")).ticks(6));

  const line = d3.line()
    .x(d => x(d.year))
    .y(d => y(d.pop));

  g.append("path")
    .datum(series)
    .attr("fill", "none")
    .attr("stroke", "#031037")
    .attr("stroke-width", 2)
    .attr("stroke-linecap", "round")
    .attr("stroke-linejoin", "round")
    .attr("d", line);

  // Endpoint labels + dots
  const first = series[0], last = series[series.length - 1];
  g.append("text")
    .attr("class", "endpoint-label")
    .attr("text-anchor", "end")
    .attr("x", x(first.year) - 6)
    .attr("y", y(first.pop) + 4)
    .text(first.pop.toLocaleString());
  g.append("text")
    .attr("class", "endpoint-label")
    .attr("text-anchor", "start")
    .attr("x", x(last.year) + 6)
    .attr("y", y(last.pop) + 4)
    .text(last.pop.toLocaleString());

  g.append("circle").attr("r", 3.5).attr("cx", x(first.year)).attr("cy", y(first.pop))
    .attr("fill", "#5541F0").attr("stroke", "#fff").attr("stroke-width", 1.5);
  g.append("circle").attr("r", 3.5).attr("cx", x(last.year)).attr("cy", y(last.pop))
    .attr("fill", "#5541F0").attr("stroke", "#fff").attr("stroke-width", 1.5);
}

// ---- Legend ---------------------------------------------------------------
function updateLegend() {
  const bins = mode === "pct" ? PCT_BINS : ABS_BINS;
  const container = d3.select("#map_legend");
  container.selectAll("svg").remove();

  const W = 300, H = 24;
  const bandW = W / COLORS.length;

  const svg = container.append("svg")
    .attr("viewBox", `0 0 ${W} ${H}`)
    .attr("preserveAspectRatio", "xMidYMid meet")
    .style("display", "block");

  // 10 colour bands.
  COLORS.forEach((c, i) => {
    svg.append("rect")
      .attr("x", i * bandW)
      .attr("y", 0)
      .attr("width", bandW)
      .attr("height", 6)
      .attr("fill", c);
  });

  // 9 labels at the boundaries between bands (between band i and band i+1).
  for (let i = 0; i < bins.length; i++) {
    const x = (i + 1) * bandW;
    const v = bins[i];
    let txt;
    if (mode === "pct") {
      txt = (v > 0 ? "+" : "") + v + "%";
    } else {
      txt = formatAbsLabel(v);
    }
    svg.append("text")
      .attr("class", "legend-number")
      .attr("text-anchor", "middle")
      .attr("x", x)
      .attr("y", 17)
      .text(txt);
  }
}

// ---- Go -------------------------------------------------------------------
init().catch(err => {
  console.error(err);
  document.body.insertAdjacentHTML("afterbegin",
    `<div style="padding:1rem;background:#fee;color:#900;">Failed to load: ${err.message}</div>`);
});
